juledwar/soufi

README.rst
soufi/__init__.py
soufi/finders/gem.py
soufi/tests/finders/test_gem_finder.py
soufi/tests/test_factory.py

Assembles Gem URLs on rubygems.org and tries to download them.  Does not support private/alternate Gem sources.
Fixes issue #2

Add a rudimentary Ruby Gem finder to Soufi

---

soufi/finders/alpine.py
soufi/tests/finders/test_alpine_finder.py

Pulls out the stored SHA-512 digests from the `APKBUILD` files, and verifies that downloaded files match.  Warns on missing checksums (as those are definitely a thing that happens) and refuses to archive files that have checksums, but do not match.
Fixes: Issue #4

Verify SHA-512 checksums on Alpine source downloads

---

README.rst
soufi/__init__.py
soufi/finder.py
soufi/finders/centos.py
soufi/finders/photon.py
soufi/finders/rhel.py
soufi/finders/yum.py
soufi/tests/finders/test_centos_finder.py
soufi/tests/finders/test_photon_finder.py
soufi/tests/finders/test_rhel_finder.py
soufi/tests/finders/test_yum_finder.py
soufi/tests/functional/test_functional.py
soufi/tests/test_factory.py

Oh boy, this one is a **MASSIVE** amount of changes, and will likely merit much discussion, as many of the decisions that went into this were made unilaterally and with zero input from anyone.
This creates a new, common finder for all Yum-based distros.  The "fast lookup" patterns have been completely discarded in favour of "fuzzy" repomd lookups, with verification via HTTP `HEAD` requests.
These finders must be initialized with a canonical search list of repository URLs containing `repodata/repomd.xml` files.  The intention is for sub-classes of this finder to provide helper methods to fill out sensible default search directories, while also allowing for users to provide their own lists (e.g., for an internal-only mirror of packages)
All of the previously-custom XPath searching code is …

Refactor Yum finders to use a common base class, add RHEL finder

---

soufi/finders/centos.py
soufi/finders/photon.py
soufi/finders/rhel.py
soufi/finders/yum.py
soufi/tests/finders/test_centos_finder.py
soufi/tests/finders/test_photon_finder.py
soufi/tests/finders/test_rhel_finder.py
soufi/tests/finders/test_yum_finder.py

- Remove the "hey I need to restart my generator" flag
- The walk* code can now just request an iterable of repos and it'll
always get handed the right generator
- Make derived Centos finder's abstract methods match the base class's
so there's no awkward arg storage and overriding
- Remove obsolete tests
- Fix breakage in tests that were testing an impossible situation where
they assumed you can have an optimal set of repos AND a custom set
(the finder's init prevents this!).

Simplify YumFinder; Everything is a generator

---

README.rst
soufi/finder.py
soufi/finders/ubuntu.py
soufi/finders/yum.py
soufi/tests/finders/test_ubuntu_finder.py
soufi/tests/finders/test_yum_finder.py

* There are roughly eleven quintillion failure modes when loading repomd, with zero of them being actionable in any realistic way.  Swallow all failures (not just HTTPErrors) and send back NoneTypes from the subprocess, the callers will similarly roll those over into "no package for you" results.
* Since the YumFinder is designed with the full expectation that a viable, persistent cache is in-place for it to do its work, add an explicit warning if a YumFinder is initialized with the null cache
* Add documentation on how to use caching.
* `launchpadlib` is not thread-safe, and its objects cannot be pickled (https://bugs.launchpad.net/launchpadlib/+bug/822847) which means we cannot use `dogpile.cache` with it, as it assumes both.
* But the call to initialize `launchpadlib` is expensive, so …

Catch all failures from repomd loads, add warnings, docs

---

soufi/finders/yum.py
soufi/tests/finders/test_yum_finder.py

Subprocesses that run successfully but generate no output should not cause a stack trace, so make them not do that.
This use case was caused by a small gap in the tests, which is also closed.
Fixes: Issue #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/23)

Bugfix: allow for empty responses from do_task

---

soufi/finders/photon.py
soufi/finders/yum.py
soufi/tests/finders/test_photon_finder.py
soufi/tests/finders/test_yum_finder.py

A couple of useful improvements:
- Failure to serialize exceptions when doing YumFinder IPC would cause the parent process to hang indefinitely waiting for a response.  Added timeouts to both ends of the queue to remediate.
- The YumFinder IPC can fail to serialize exceptions in some cases.  Add a fallback "generic" exception in those cases.
- Photon OS does not reliably publish repodata for all releases any longer, so double-check all candidate repo dirs before attempting to use them.
Fixes: Issue #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/26)

General improvements to PhotonFinder, YumFinder

---

soufi/finders/centos.py
test-requirements.txt

Drive-by: update the version of Black used for tests, for compatibility with modern Click.
Fixes Issue #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/30)

Bugfix: Use canonical URLs for CentOS auto-discovery

---

soufi/exceptions.py
soufi/tests/finders/test_alpine_finder.py
soufi/tests/test_finder_base.py
test-requirements.txt

One of the more common causes of `DownloadError` exceptions in the wild is `HTTPError` exceptions.
Surface the status code from the HTTP response as a convenience to callers.
Drive-by: update the version of Black used for tests, for compatibility with modern Click.
Fixes Issue #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/28)

Add a status_code attribute to DownloadError exceptions

---

soufi/finders/yum.py
soufi/tests/finders/test_yum_finder.py
tox.ini

Make a good-faith effort to catch the `RuntimeError` thrown when improperly invoking the YumFinder on non-Linux platforms, and present a useful error message to the user.
Fixes: Issue #31
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/34)

Provide a more helpful error message on spawn() failures

---

soufi/finders/python.py
soufi/tests/finders/test_python_finder.py

Spotted while running the functional tests; packages no longer necessarily have a `releases` field containing the URL, there is a new field called `urls` that contains a list of URLs/hashes.
Update the Python finder to make use of it should it find one, and add unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/36)

Python: Accomodate `urls` field in PyPI responses

---

soufi/finders/centos.py
soufi/tests/finders/test_centos_finder.py

Noticed when running the functional tests.  Also clean up a bunch of unit tests that were enforcing bad behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/37)

Fix a double-delimiter bug in the CentOS finder

---

soufi/finders/yum.py
soufi/tests/finders/test_yum_finder.py

Implement our own XML fetch/parse routines for consuming repomd data, and create a simple lookup dict from the results rather than trying to shoehorn in use of the `repomd.findall` library call.
This yields a 30%-50% speedup in the functional tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/38)

Refactor the YumFinder

---

HACKING.rst
README.rst
soufi/finder.py
soufi/finders/alma.py
soufi/finders/centos.py
soufi/finders/photon.py
soufi/functional/test_functional.py
soufi/testing/base.py
soufi/tests/finders/test_alma_finder.py
soufi/tests/finders/test_centos_finder.py
soufi/tests/finders/test_debian_finder.py
soufi/tests/finders/test_gem_finder.py
soufi/tests/finders/test_golang_finder.py
soufi/tests/finders/test_java_finder.py
soufi/tests/finders/test_npm_finder.py
soufi/tests/finders/test_photon_finder.py
soufi/tests/finders/test_python_finder.py
soufi/tests/finders/test_rhel_finder.py
soufi/tests/finders/test_yum_finder.py
soufi/tests/test_factory.py

A sensibly-distributed little RPM-based distro:
https://repo.almalinux.org/
This finder tries to take the best bits from the UBI, CentOS, and Photon OS finders to make something small, no-nonsense, and performant.
Drive-by: banish all now-unused `nosec` markers, and references to silly things Bandit used to do.
Fixes: Issue #40
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/48)

Add a finder for Alma Linux

---

README.rst
soufi/finder.py
soufi/finders/almalinux.py
soufi/functional/test_functional.py
soufi/tests/finders/test_alma_finder.py
soufi/tests/test_factory.py

According to their trademark usage policy at
https://almalinux.org/p/the-almalinux-os-trademark-usage-policy/ the proper name of the distro is "AlmaLinux OS", so let's respect that.
Relates: Issue #40
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/52)

Bugfix: s/Alma/AlmaLinux/g

---

soufi/__init__.py

commit b12334e94656cec91151ea297e39b298401f9ac4 introduced a small regression with importing the library; ensure that `soufi.exceptions`, `soufi.finders`, etc., will still work when importing the top-level library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/53)

Bugfix: Keep `import soufi` as a useable/useful entrypoint

---

soufi/cli.py
soufi/finders/alpine.py
soufi/finders/yum.py

This setting is global, so it is bad form for libraries to alter it; the top-level application should be responsible for such things.
Fixes: Issue #56
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/57)

Move the `warnings.formatwarning` call into the CLI

---

soufi/finders/alpine.py

Python 3.8 is the minimum supported version, so this tech debt can be paid off pretty easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/58)

chore: simplify Alpine finder

---

.github/workflows/tests.yml
.vscode/settings.json
README.rst
pyproject.toml
soufi/cli.py
soufi/finder.py
soufi/finders/php_pecl.py
soufi/testing/data/phppecl/ncurses_1.0.2.xml
soufi/tests/finders/test_phppecl_finder.py
soufi/tests/test_factory.py

Searches the index at pecl.php.net for the requested package.
Drive-by changes:
- Add testing on Python 3.12
- Ensure the local hatch env uses the -cli requirements
- Fix the README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/61)

Add a PHP PECL finder

---

soufi/finders/rhel.py

Update default repo list to use the set described in https://access.redhat.com/articles/4238681
- Fix UBI 8 base OS repo location
- Remove dev tools repo for UBI 7
- Add UBI 9 repos
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/juledwar/soufi/64)

Update UBI repo lists
